### ISSUE TITLE
1. Cacher le bouton 'supprimer' si l'utilisateur n'a pas le droit

### ISSUE THREAD

**Issue by Avasam** [THER4ID/TP_WEB_SAM_SIMON#2]
Lorsqu’on affiche les exemplaires d’un livre, un lien « supprimer » apparaît pour chaque
exemplaire. On désire que ce lien n’apparaisse pas si l’utilisateur n’a pas le droit de
supprimer l’exemplaire (actuellement, l’application refuse quand même la suppression);

**Comment by THER4ID** [comment]
c'est reglé
